# Python Numpy
### Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialise numpy arrays from nested python lists and access its elements.

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# Multidimensinal numerical array
# Remeber to pass it as a list
b = np.array([(1,2,3),(4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
print(a.itemsize)
print(b.itemsize)

4
4


In [4]:
import numpy as np 

import time
import sys

# More in memory
S = range(1000)
print(S)
print(sys.getsizeof(S))
print(sys.getsizeof(S)*len(S))

# Less in memory
D=np.arange(1000)
print(D.size * D.itemsize)

range(0, 1000)
24
24000
4000


In [5]:
SIZE = 1000000

L1 = range(SIZE) 
L2 = range(SIZE)

A1 = np.arange(SIZE)
A2 = np.arange(SIZE)

start = time.time()
result = [x + y for x,y in zip(L1,L2)]
print((time.time() - start) * 1000)

start = time.time()
result = A1 + A2
print((time.time() - start) * 1000)

160.5849266052246
32.89484977722168


In [6]:
zip(L1,L2)
# Zips two lists
# list(zip(L1,L2))   #Long output

# Python Numpy operations

In [7]:
a = np.array([(1,2,3),(4,5,6),(7,8,9)])
print(a.ndim)
a.size

2


9

In [8]:
a = np.array([(1,2,3)])
print(a.itemsize)
print(a.dtype)

4
int32


In [9]:
a = np.array([(1,2,3),(4,5,6)])
print(a.size)
print(a.shape)

6
(2, 3)


In [10]:
# Reshape & Slicing
a = np.array([(8,9,10),(11,12,13)])
# DAMN


In [11]:
a = np.array([(1,2,3,4),(3,4,5,6)])
print(a)
print(a[1,2])
print(a[1:2])

[[1 2 3 4]
 [3 4 5 6]]
5
[[3 4 5 6]]


In [12]:
a = np.array([(8,9,11),(10,11,12),(12,13,13,),(3,5,6)])
print(a)
print()
print(a[0:3,1])

[[ 8  9 11]
 [10 11 12]
 [12 13 13]
 [ 3  5  6]]

[ 9 11 13]


## Linspace

In [13]:
list(range(0,10,3))

[0, 3, 6, 9]

In [14]:
# First and last are fixed
# Remaining middle are equally spaced
a = np.linspace(1,1000,15)
print(a)

[   1.           72.35714286  143.71428571  215.07142857  286.42857143
  357.78571429  429.14285714  500.5         571.85714286  643.21428571
  714.57142857  785.92857143  857.28571429  928.64285714 1000.        ]


In [15]:
a = np.array([19,23,56,10,19,76,84,90,12])
print(a.min())
print(a.max())
print(a.sum())
print(a.mean())
print(np.sqrt(a))
print(np.std(a))  #Sqrt of Variance

10
90
389
43.22222222222222
[4.35889894 4.79583152 7.48331477 3.16227766 4.35889894 8.71779789
 9.16515139 9.48683298 3.46410162]
31.179686327899013


### Calculating mean, meadian with numpy inbuilt functions

In [16]:
# 1d array
# DAMN

In [17]:
# DAMN
# 2d array
arr = [[14,17,12,33,44],
        [15,6,27,8,19],
        [23,2,54,1,4]]
# Median and Mean along the axis = 0
print("\nmeadian of arr,axis = 0",np.median(arr,axis=0))
print("\nmean of arr,axis = 0",np.mean(arr,axis=0))


# Median and Mean along the axis = 1
print("\nmeadian of arr,axis = 1",np.median(arr,axis=1))
print("\nmean of arr,axis = 1",np.mean(arr,axis=1))


# Median and Mean along the axis = 2
print("\nmeadian of arr,axis = 2",np.median(arr,axis=2))
print("\nmean of arr,axis = 2",np.mean(arr,axis=2))


meadian of arr,axis = 0 [15.  6. 27.  8. 19.]

mean of arr,axis = 0 [17.33333333  8.33333333 31.         14.         22.33333333]

meadian of arr,axis = 1 [17. 15.  4.]

mean of arr,axis = 1 [24.  15.  16.8]


AxisError: axis 2 is out of bounds for array of dimension 2

In [18]:
# 

In [19]:
x = np.array([(1,2,3),(3,4,5)])
y = np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


In [20]:
import math

# Ravel converts numpy array into single column
x = np.array([(1,2,3),(3,4,5)])
print(x)
print(x.ravel())

[[1 2 3]
 [3 4 5]]
[1 2 3 3 4 5]
