# Intro to Pandas & data visualization

In [1]:
# pip install pandas
import pandas as pd

## Data Structures in Pandas
### Dataframe and series 
### A Dataframe in a 2d array of values with both a row and a column index 
### A Series is a 1d array of values with an index 

## From Stackoverflow,
### The primary pandas data structure. So, the Series is the data structure for a single column of a DataFrame , not only conceptually, but literally, i.e. the data in a DataFrame is actually stored in memory as a collection of Series . Analogously: We need both lists and matrices, because matrices are built with lists

## Series

In [4]:
import pandas as pd
S = pd.Series([11,28,72,3,5,8])
print(S)

0    11
1    28
2    72
3     3
4     5
5     8
dtype: int64


In [5]:
print(S.index)
print(S.values)

RangeIndex(start=0, stop=6, step=1)
[11 28 72  3  5  8]


## Difference between Numpy arrays and Series

In [6]:
import numpy as np
X = np.array([11,28,72,3,5,8])
print(X)
print(S.values)
# Both are same type
# Pandas is written on top of Numpy
print(type(X))
print(type(S.values))


[11 28 72  3  5  8]
[11 28 72  3  5  8]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [8]:
fruits = ['apples','oranges','cherries','pears']
S = pd.Series([20,33,52,10],index = fruits)
S2 = pd.Series([17,13,31,32],index = fruits)
print(S + S2)
print("sum of S:",sum(S))

apples      37
oranges     46
cherries    83
pears       42
dtype: int64
sum of S: 115


In [9]:
fruits = ['apples','oranges','cherries','pears']
fruits2 = ['raspberries','oranges','cherries','pears']

S = pd.Series([20,33,52,10],index = fruits)
S2 = pd.Series([17,13,31,32],index = fruits2)
print(S + S2)

apples          NaN
cherries       83.0
oranges        46.0
pears          42.0
raspberries     NaN
dtype: float64


In [10]:
fruits = ['apples','oranges','cherries','pears']
fruits_tr = ['elma','portakal','kiraz','armut']

S = pd.Series([20,33,52,10],index = fruits)
S2 = pd.Series([17,13,31,32],index = fruits_tr)
print(S + S2)

apples     NaN
armut      NaN
cherries   NaN
elma       NaN
kiraz      NaN
oranges    NaN
pears      NaN
portakal   NaN
dtype: float64


## Series Indexing

In [11]:
a = [1,2,3,4]
a[0]

1

In [16]:
S

apples      20
oranges     33
cherries    52
pears       10
dtype: int64

In [15]:
print('Single Indexing',S['apples'])
print('@@@@@@@@@@@@')
print('Multi Indexing\n' ,S[['apples','oranges','cherries']])

Single Indexing 20
@@@@@@@@@@@@
Multi Indexing
 apples      20
oranges     33
cherries    52
dtype: int64


## pandas.Series.apply

In [17]:
# Ex
print(S)
S.apply(np.log)

apples      20
oranges     33
cherries    52
pears       10
dtype: int64


apples      2.995732
oranges     3.496508
cherries    3.951244
pears       2.302585
dtype: float64

In [18]:
S

apples      20
oranges     33
cherries    52
pears       10
dtype: int64

In [20]:
# def fn:
#     if x > 50:
#         return x
#     else:
#         return x + 10

SyntaxError: invalid syntax (<ipython-input-20-a87eb0079a67>, line 1)

In [19]:
S.apply(lambda x: x if x > 50 else x + 10)

apples      30
oranges     43
cherries    52
pears       20
dtype: int64

In [21]:
S[S>30]

oranges     33
cherries    52
dtype: int64

In [22]:
"apples" in S

True

In [ ]:
# Creating Series Objects from dictionaries
cities = {"London": 8615246,
          "Berlin": 8615246,
          "London": 8615246,
          "London": 8615246,
          "London": 8615246,
          "London": 8615246,
          "London": 8615246,
          "London": 8615246,
          "Milan": 8615246,
                            }
# DAMN

In [ ]:
my_cities = ['London','Paris','Berlin','Hamburg']
my_cities_series = pd.Series(cities,index = my_cities)
my_cities_series

In [ ]:
my_cities = ['London','Paris','Zurich','Berlin','Stuttgart','Hamburg']
my_cities_series = pd.Series(cities,index = my_cities)
# DAMN


In [ ]:
print(my_series_series.dropna())

In [ ]:
print(my_series_series.fillna(10))

In [ ]:
missing_cities = {'Stuttgart':597939,'Zurich':378884}
my_cities_series.fillna(missing_cities)